import {
  FaLaptopCode,
  FaChess,
  FaBasketballBall,
  FaTheaterMasks,
  FaVolleyballBall,
  FaFootballBall,
} from "react-icons/fa";
import { FaPencil } from "react-icons/fa6";
import { GiMicrophone, GiSoccerBall } from "react-icons/gi";
import { staffInfo } from "../types/information";

export const staffCategories: staffInfo[] = [
  {
    category: "Founder",
    members: [
      {
        name: "Justin Perez",
        role: "Co-Founder/ CEO",
        bio: "Leads with heart, empowering kids to thrive beyond limits",
        image: "/images/Staff_Photos/Justin_P.jpg",
        moreInfo: {
          email: "justin@iacafterschools.com",
          phone: "(714) 509-0069",
          text: "Justin's journey to founding IAC was inspired by a career defined by dedication and noteworthy achievements. Prior to establishing IAC, he distinguished himself at a previous organization where his exceptional teaching skills earned him recognition in the Tustin Weekly newspaper. In that moment of recognition, Justin passionately described chess as a transformative pursuit, highlighting its profound impact on life skills and strategic thinking. Building on this success, his unwavering commitment to education was honored with the prestigious Millennium Leadership Award from Marin Millennium, celebrating his exemplary leadership and tireless dedication to nurturing future generations. Motivated by these experiences, Justin envisioned IAC as an inclusive educational platform that caters to the diverse needs and interests of students. <br/> Justin’s vision for IAC was not limited to traditional education; it was a mission to create an environment where learning transcends subject matter and imparts life skills that students carry into adulthood. At the heart of this vision is a commitment to fostering a platform where students can connect with instructors who are not only knowledgeable but also supportive mentors. These mentors guide and inspire students, cultivating a passion for learning and a deeper understanding of the subjects they pursue. Justin dreamed of IAC as a safe space where students could explore their interests, gain meaningful insights, and grow both academically and personally.<br/> Central to Justin’s approach is the belief that education should equip students with practical skills that prepare them for real-world challenges. He aspired for IAC to be a place where students not only excel in academic pursuits but also develop the critical thinking and resilience necessary for professional and personal success. His dedication to a holistic approach in education underscores his commitment to the growth and development of every student under the IAC umbrella.<br/>In pursuit of his vision, Justin strives to build enduring trust with partners and collaborators. His deep-rooted passion for teaching and genuine care for his students fuel his dedication to nurturing an environment where growth and learning thrive. Justin’s vision for IAC's future is ambitious; he seeks to broaden the company’s reach to include more schools and expand the curriculum to encompass an even wider array of subjects. His relentless pursuit of excellence and drive to touch more students’ lives reflect his commitment to enhancing educational experiences and preparing learners for the future.<br/>Within the IAC community, Justin is a respected leader and source of inspiration. Instructors turn to him for guidance, leadership, and the invaluable insights he offers to help them excel as educators and mentors. His vast experience and steadfast commitment to education have made him a beacon of excellence, shaping the growth and development of those under his mentorship. Justin’s visionary approach motivates everyone within IAC to aim higher, pursue excellence, and continuously strive for self-improvement. Under his leadership, IAC is more than an educational institution; it is a vibrant, evolving community that inspires its members to push boundaries and achieve new levels of success.<br/>In this atmosphere of continuous learning and transformation, Justin’s influence is profound, serving as a reminder that the pursuit of knowledge and excellence is a lifelong journey. His leadership propels IAC forward, enriching the educational landscape and nurturing the potential of every student and instructor who is part of the IAC family.",
          images: [
            "/images/Staff_Photos/Justin/image16.jpg",
            "/images/Staff_Photos/Justin/image13.jpg",
            "/images/Staff_Photos/Justin/image00.jpg",
            "/images/Staff_Photos/Justin/image14.jpg",
            "/images/Staff_Photos/Justin/image11.jpg",
            "/images/Staff_Photos/Justin/image12.jpg",
            "/images/Staff_Photos/Justin/image20.jpg",
            "/images/Staff_Photos/Justin/image15.jpg",
            "/images/Staff_Photos/Justin/image19.jpg",
            "/images/Staff_Photos/Justin/image21.jpg",
            "/images/Staff_Photos/Justin/image17.jpg",
            "/images/Staff_Photos/Justin/image18.jpg",
          ],
        },
      },
      {
        name: "Jason Perez",
        role: "Co-Founder",
        bio: "Provides steadfast support to help kids thrive",
        image: "/images/Staff_Photos/Jason_P.jpg",
        moreInfo: {
          text: "When Justin set out to establish IAC, his brother, Jason Perez, was not just a supporter but an indispensable part of that journey as his co-founder and unwavering champion. From the earliest stages of building the company, Jason was the steady anchor on whom Justin relied, offering unyielding support, insightful guidance, and relentless encouragement. His belief in Justin’s vision was profound and absolute. Jason recognized the immense potential in what Justin was creating and, without hesitation, dedicated himself to making that vision a reality. He understood that the journey would be filled with challenges, but his confidence in their shared mission drove him to give his all, day after day. While Justin emerged as the face of IAC, leading with his innovative approach to education, Jason worked diligently behind the scenes to ensure the company had the stability and resources needed to flourish. His quiet strength, strategic thinking, and tireless dedication were fundamental in building the strong foundation on which IAC would stand.<br/>As co-founder, Jason brought a unique blend of practical knowledge, strategic insight, and unwavering dedication that perfectly complemented Justin’s passion for teaching. He understood the nuances of starting a new venture—the long hours, the uncertainties, and the need for resilience—and was there at every turn to navigate obstacles and celebrate successes. Far from diminishing his impact, Jason’s work behind the scenes amplified it. He was not only a pillar of support but a force of execution, enabling Justin to shine as the leader while knowing that IAC’s operations were solid and its growth sustainable.<br/>Jason’s contributions went far beyond the financial realm; he was Justin’s confidant, sounding board, and motivator. He made personal sacrifices that underscored his commitment to IAC’s mission and to Justin’s dream. His belief in the transformative power of education was as deep as his dedication to ensuring that IAC could achieve its fullest potential. Jason’s generosity of spirit, boundless dedication, and willingness to go above and beyond propelled the company forward during its formative years. It was his drive and shared vision that helped translate ambition into tangible progress.<br/>Although Jason preferred to stay out of the spotlight, his influence permeates every part of IAC’s story. His quiet commitment was woven into the fabric of the company’s growth, ensuring that every decision and every milestone was backed by his unwavering support. His presence allowed Justin to focus on what he did best—creating an educational environment that was inclusive, innovative, and responsive to the unique needs of students. The synergy between the two brothers was a perfect blend of vision and execution, each playing a role that complemented and elevated the other. This dynamic laid the groundwork for IAC’s success and set the tone for its growth.<br/>Jason’s legacy at IAC is one of quiet strength, steadfast dedication, and enduring impact. As co-founder, he was more than a behind-the-scenes contributor; he was a cornerstone of the company’s early achievements. His belief in Justin’s vision was the driving force behind his unwavering support, and his role in helping turn that vision into a reality is irreplaceable. The profound bond between the brothers, marked by mutual respect and shared determination, created an atmosphere where IAC could thrive. Jason’s influence extended beyond just the initial stages of development; it became embedded in the company’s ethos, inspiring a culture of support, resilience, and ambition that resonates throughout IAC to this day.<br/>His contributions left an indelible mark not only on the company itself but also on everyone who has been part of its journey. In every aspect of IAC’s evolution—from the trust built with students and families to the innovative curriculum that sets it apart—Jason’s dedication is evident. His steadfast commitment to supporting the vision, ensuring operational soundness, and fostering an environment of growth and learning helped shape IAC into what it is today: a beacon of educational excellence.",
          images: [],
        },
      },
    ],
  },
  {
    category: "Senior Instructors",
    members: [
      {
        name: "Tina Huynh",
        role: "Chief Operating Officer",
        bio: "Oversees operations, engineering, and administration seamlessly.",
        image: "/images/Staff_Photos/Tina.jpg",
        icons: [FaLaptopCode, FaPencil, FaChess],
        moreInfo: {
          email: "tina@iacafterschools.com",
          phone: "(714) 858-2418",
          text: "Tina's journey into the world of education began during her middle school years when she volunteered at summer camps held at the University of California, Irvine. It was there that she first discovered her passion for teaching. She found immense joy in helping her fellow students grasp subjects she was knowledgeable about and experienced the satisfaction of giving back to others. Upon graduating from high school, Tina dedicated even more of her time to introducing elementary and middle school students to the world of STEM, with a particular focus on software engineering and coding. She cherished the moments when her students had those 'aha' moments, grasping complex concepts, and was elated to see their continued enthusiasm for coming to her classes. Being a first-generation software engineer herself, Tina is deeply committed to supporting the younger generations as they follow in her footsteps and strive to make a positive impact in their community.<br/>Tina’s journey in education began with a spark of passion during her middle school years when she volunteered at summer camps hosted by the University of California, Irvine. It was there that she first discovered the deep fulfillment of teaching—seeing students’ eyes light up as they understood new concepts and feeling the joy of giving back. This early experience laid the foundation for a lifelong commitment to empowering young minds. After high school, Tina devoted even more time to guiding elementary and middle school students into the fascinating world of STEM, especially focusing on software engineering and coding. She cherished those transformative “aha” moments when students grasped complex ideas and felt profound pride in witnessing their growing excitement and eagerness to learn. As a first-generation software engineer, Tina is fiercely dedicated to inspiring future generations, mentoring them as they strive to make meaningful impacts in their communities.<br/>Tina embodies determination, resilience, and unwavering integrity. She stands strong for justice, never hesitating to take a firm stance for what’s right. Her keen observational skills and empathetic nature make her an insightful and perceptive mentor. When the stakes are high, Tina approaches challenges with assertiveness and unwavering resolve. Dependable and loyal, she is the ally who will go above and beyond, delivering excellence that exceeds expectations. With Tina on your side, you can trust that every endeavor will be approached with passion, precision, and the highest level of dedication.<br/>Within IAC, Tina plays a pivotal role, working alongside Justin to oversee a wide array of responsibilities. From administrative management and curriculum design to website optimization and employee training, her impact is felt in every aspect of the organization. Tina is not just a supportive contributor; she is a proactive change agent, offering invaluable insights and expert advice that empower Justin and the entire team to make informed and strategic decisions.<br/>As a full-stack web developer, Tina’s dedication to web development shines through her meticulous work on the company website, which she built from the ground up and continues to enhance and maintain. Her unique skill set in both front-end and back-end development allows her to create a cohesive, seamless digital experience for IAC. With an eye for detail and design, she crafts user interfaces that are both visually appealing and highly functional, ensuring an intuitive and engaging experience for users. Tina’s ability to unify the front-end and back-end creates a synchronized digital platform that reflects her holistic approach and technical expertise.<br/>Tina’s extensive experience and thorough understanding of instructional expectations enable her to consistently meet and exceed the highest standards. Her dedication and knowledge make her an essential force within the IAC team, fostering excellence and driving the success of the organization. With her guidance and unwavering support, IAC continues to thrive, delivering quality and impact that resonate far beyond the classroom.",
          images: [
            "/images/Staff_Photos/Tina/image4.jpg",
            "/images/Staff_Photos/Tina/image9.jpg",
            "/images/Staff_Photos/Tina/image8.jpg",
            "/images/Staff_Photos/Tina/image3.jpg",
            "/images/Staff_Photos/Tina/image1.jpg",
            "/images/Staff_Photos/Tina/image2.jpg",
            "/images/Staff_Photos/Tina/image7.jpg",
            "/images/Staff_Photos/Tina/image6.jpg",
            "/images/Staff_Photos/Tina/image5.jpg",
          ],
        },
      },
      {
        name: "Mike Ash",
        role: "Director of Chess Operations",
        bio: "Leads chess operations with expertise and passion, inspiring growth and strategy.",
        image: "/images/Staff_Photos/Mike.jpg",
        icons: [GiSoccerBall, FaChess],
        moreInfo: {
          text: "Mike’s partnership with Justin, spanning over two decades, reflects an unshakeable bond built on trust, respect, and shared dedication. Through these years, Mike has been the cornerstone of their journey, embodying extraordinary loyalty, perseverance, and passion. His path from a devoted team member to an indispensable leader within the company is marked by tireless effort, steadfast determination, and an unwavering love for teaching chess. Mike’s role transcends his unmatched expertise as the most experienced and skilled instructor; he is the driving force behind our educational mission. Every class he leads radiates his joy for teaching, demonstrating that for Mike, teaching is not just a profession but a true calling. His passion to inspire and support his students’ growth shines through in every lesson, making him invaluable to our organization.<br/>Mike’s impact extends far beyond his profound understanding of chess. He teaches more than the strategies of the game; he instills resilience, strategic thinking, and sportsmanship, equipping students with life skills that resonate beyond the classroom. His instruction is enriched by deep empathy and an innate ability to connect with learners, fostering a supportive environment where they can thrive. This combination of compassion and expertise has made Mike an unparalleled mentor, not just to students but to new instructors who look to him for guidance. He leads by example, embodying the core values of our organization and ensuring that every instructor aligns with our high standards. Mike’s mentorship helps integrate new team members seamlessly, building their confidence and enhancing their teaching approach.<br/>In everything he does, Mike sets the standard for dedication. He doesn’t just fulfill expectations; he consistently surpasses them, establishing a benchmark of excellence that others strive to meet. His reliability is the foundation on which our programs are built, offering certainty and trust in every class he leads. Mike’s commitment and work ethic have earned him the reputation of being the most dependable instructor on our team, a testament to his unwavering integrity and relentless pursuit of quality.<br/>Mike’s influence is deeply felt throughout the company. His leadership extends beyond teaching, serving as a source of motivation and encouragement for all who have the privilege of working with him. He exemplifies what it means to be passionate, driven, and committed to one’s craft. His presence reassures both new and seasoned instructors, enabling them to deliver exceptional experiences to students with confidence, knowing they have an irreplaceable mentor to support them.<br/>Mike’s dedication, mentorship, and passion make him an extraordinary asset whose contributions are beyond measure. His influence will continue to shape the future of IAC, ensuring that the legacy of excellence, compassion, and inspiration he embodies lives on in every corner of our organization.<br/>",
          images: [
            "/images/Staff_Photos/Mike/image1.jpg",
            "/images/Staff_Photos/Mike/image2.jpg",
            "/images/Staff_Photos/Mike/image9.jpg",
            "/images/Staff_Photos/Mike/image3.jpg",
            "/images/Staff_Photos/Mike/image4.jpg",
            "/images/Staff_Photos/Mike/image6.jpg",
            "/images/Staff_Photos/Mike/image7.jpg",
            "/images/Staff_Photos/Mike/image8.jpg",
            "/images/Staff_Photos/Mike/image5.jpg",
          ],
        },
      },
      {
        name: "Tommy Owens",
        role: "Director of Basketball Operations",
        bio: "Leads basketball operations with dedication and a passion for excellence.",
        image: "/images/Staff_Photos/Tommy.jpg",
        icons: [FaBasketballBall, FaChess],
        moreInfo: {
          text: "Tommy’s journey with our organization is a story of unwavering dedication, boundless passion, and a steadfast commitment to mentorship. With years of service marked by excellence, Tommy stands as a pillar within our community. His extensive experience across various disciplines, including chess, volleyball, soccer, and basketball, showcases his versatility and deep-rooted commitment to education. Yet, it is basketball that truly captures his heart. His profound knowledge of the game—encompassing both technique and strategy—has solidified his reputation as the go-to expert and earned him the distinguished title of Director of Basketball Operations. In this leadership role, Tommy not only spearheads the basketball program but also shapes its vision and ensures its continued growth and success.<br/>One of Tommy’s most defining qualities is his dedication to mentorship. New instructors embarking on their teaching journey are met with the privilege of learning under Tommy’s expert guidance. He goes beyond imparting technical knowledge; he shares insights into effective classroom management, teaching styles, and the art of connecting with students. From meticulously designed drills to comprehensive gameplay techniques, Tommy’s mentorship equips instructors with the tools and confidence they need to excel. His approach is rooted in compassion, empathy, and a genuine desire to see others grow, both as educators and as individuals.<br/>Tommy’s influence stretches far beyond the basketball court. He embodies leadership marked by motivation, determination, and an unwavering drive to elevate everyone around him. His open-door policy fosters a welcoming and supportive environment where communication thrives and team members feel valued. This policy isn’t just a figure of speech—it reflects his commitment to being available, present, and a reliable source of guidance. Tommy’s approach cultivates trust and encourages collaboration, nurturing a strong sense of community and belonging among his colleagues.<br/>Drawing from his deep understanding of the company’s expectations and operational intricacies, Tommy acts as a guiding force for newcomers navigating their path within the organization. He shares his wealth of knowledge with unmatched dedication, helping others chart their own courses of growth and success. His mentorship is a testament to his belief in empowering others and fostering an atmosphere of continuous improvement. Tommy’s unwavering presence and support inspire confidence and encourage new instructors to rise to their full potential.<br/>The transformative impact of Tommy’s work is perhaps most evident in the youth programs he leads. Since joining our organization, the growth in his class sizes has been phenomenal, tripling under his stewardship. What sets him apart is his unique ability to forge connections with young players. His teaching transcends skill-building; he instills a genuine love for the game, igniting a passion that stays with them long after they leave his class. Students under Tommy’s instruction learn essential basketball skills—dribbling, passing, shooting, and effective teamwork—while absorbing lessons in discipline, resilience, and sportsmanship. They leave not just as better athletes but as more confident, well-rounded individuals with a deeper appreciation for the values the game embodies.<br/>Tommy’s dedication, compassion, and leadership make him a cherished mentor and an irreplaceable asset to our organization. His relentless pursuit of excellence, coupled with his empathetic and motivational nature, sets a standard that resonates throughout our programs. He is the heart of our basketball initiative and an inspiring force whose influence shapes not only the future of young athletes but also the professional growth of his peers. Tommy’s legacy is one of profound impact—one that will continue to elevate our programs and enrich the lives of everyone he mentors for years to come.",
          images: [
            "/images/Staff_Photos/Tommy/image1.jpg",
            "/images/Staff_Photos/Tommy/image2.jpg",
            "/images/Staff_Photos/Tommy/image3.jpg",
            "/images/Staff_Photos/Tommy/image4.jpg",
            "/images/Staff_Photos/Tommy/image5.jpg",
            "/images/Staff_Photos/Tommy/image6.jpg",
            "/images/Staff_Photos/Tommy/image7.jpg",
            "/images/Staff_Photos/Tommy/image8.jpg",
            "/images/Staff_Photos/Tommy/image9.jpg",
          ],
        },
      },
      {
        name: "Layla Kurokawa",
        role: "Director of Performing Arts Operations",
        bio: "Manages performing arts operations with dedication and vision.",
        image: "/images/Staff_Photos/Layla.jpg",
        icons: [FaTheaterMasks],
        moreInfo: {
          text: "Layla’s role as the Director of Performing Arts Operations at IAC is much more than a job title—it is a testament to her profound impact on the organization. This esteemed position reflects her pivotal contributions that have broadened the scope of IAC, ushering it into the dynamic world of performing arts and drama. Through her visionary leadership, Layla has created new pathways for students to explore their artistic abilities and express themselves creatively. Her influence has opened doors to a realm where students can engage with their passions, fostering a love for the arts that extends beyond the classroom.<br/>One of Layla’s most notable achievements lies in her dedication to mentoring and training new instructors, particularly those specializing in performing arts education. Layla embodies more than just an instructor; she is a mentor who meticulously imparts the values, standards, and high expectations that are the hallmark of IAC’s commitment to educational excellence. Under her expert guidance, new hires receive thorough training that equips them not just to meet but to exceed the company’s standards. Layla’s tireless dedication to nurturing new talent underscores her passion for cultivating future educators and performers who carry forward the principles of creativity and excellence.<br/>Layla’s influence reaches far beyond her own classes, touching every aspect of IAC’s performing arts programs. Her dedication to continuously refining and enhancing these programs ensures that students receive the highest quality education and opportunities. Her passion radiates throughout the institution, enriching students' experiences and nurturing a vibrant, artistic community.Known for her compassionate and inclusive approach, Layla is committed to ensuring that every student feels valued and seen.Her dedication to inclusivity knows no limits—she makes it her mission to accommodate the diverse needs of students, whether they are naturally extroverted or prefer to express themselves more quietly.<br/> In Layla’s classes, education is never a one- size - fits - all approach.She celebrates diversity and emphasizes the unique qualities and strengths of each student.Layla’s belief in the potential of every individual fuels her efforts to create a space where these unique traits can shine.Her dedication comes to life most vividly during the end- of - session showcase.This event is more than a performance; it is a heartfelt celebration of each student’s journey under Layla’s nurturing and attentive guidance.The showcase is designed to spotlight not just a few standout performers but to celebrate every student, acknowledging their growth, talents, and individuality.<br/> In Layla’s classroom, artistic growth is intertwined with the development of confidence and self- esteem.Her philosophy, rooted in the recognition and celebration of individuality, distinguishes her as an extraordinary and compassionate educator.Layla’s students leave her classes not only with enhanced artistic skills but with a newfound sense of self - worth and belief in their abilities.Her approach leaves an indelible mark on the hearts and minds of her students, making her a true beacon of inspiration and an invaluable leader within IAC.",
          images: [
            "/images/Staff_Photos/Layla/image1.jpg",
            "/images/Staff_Photos/Layla/image2.jpg",
            "/images/Staff_Photos/Layla/image5.jpg",
            "/images/Staff_Photos/Layla/image3.jpg",
            "/images/Staff_Photos/Layla/image6.jpg",
            "/images/Staff_Photos/Layla/image7.jpg",
            "/images/Staff_Photos/Layla/image4.jpg",
            "/images/Staff_Photos/Layla/image8.jpg",
            "/images/Staff_Photos/Layla/image9.jpg",
          ],
        },
      },
      {
        name: "Cory Camama",
        role: "Director of Volleyball Operations",
        bio: "Oversees volleyball operations with extensive experience and expertise.",
        image: "/images/Staff_Photos/Cory.jpg",
        icons: [FaVolleyballBall],
        moreInfo: {
          text: "Cory has quickly established himself as a vital member of our organization, bringing his passion and expertise in volleyball to the forefront of our sports programs. His deep understanding of the game, from the fundamentals to advanced strategies, has made him an indispensable coach and mentor to both his students and fellow instructors. Cory’s dedication to the sport is evident in every aspect of his work, and his impact on our volleyball program has been nothing short of transformative. Cory's classes have seen remarkable growth under his leadership, with more students than ever eager to learn from him. His ability to connect with young athletes, instilling in them not only the technical skills of volleyball but also a genuine love for the game, sets him apart as a coach. Students in Cory’s classes leave with sharpened skills in serving, passing, setting, and spiking, but more importantly, they develop a strong sense of teamwork, discipline, and sportsmanship. Cory’s approach to coaching goes beyond skill development—he teaches life lessons that extend far beyond the volleyball court, fostering a deep appreciation for the game and the values it represents.<br/>One of Cory’s standout qualities is his commitment to mentorship. He takes an active role in guiding new instructors, sharing his knowledge and experience to help them excel in their roles. Cory’s mentorship goes beyond teaching techniques; he offers invaluable insights into classroom management and effective coaching styles, ensuring that our new hires are well-prepared to deliver high-quality instruction. His open-door policy and willingness to support his colleagues at any time create a welcoming and collaborative atmosphere within the organization. Cory’s accessibility and generosity have fostered a sense of community and belonging among the team, making him a trusted mentor and leader. Cory's passion for volleyball and his dedication to his students have had a profound impact on our sports program. His contributions are a testament to his commitment to excellence, both in coaching and in mentoring the next generation of instructors. Cory's influence extends far beyond the volleyball court, shaping the lives of his students and colleagues alike. He is not just a coach; he is a mentor, a leader, and an invaluable asset to our organization, whose contributions have significantly enhanced the quality of our sports programs.",
          images: [],
        },
      },
      {
        name: "Jason Michael",
        role: "Technical Advisor",
        bio: "Provides expert technical guidance and innovative solutions.",
        image: "/images/Staff_Photos/JasonM.jpg",
        icons: [FaLaptopCode],
        moreInfo: {
          text: "As Justin embarked on his visionary mission to create an impactful educational landscape for the younger generation, Jason Michael emerged as the driving force behind its success. Jason’s unwavering dedication, boundless generosity, and profound technical expertise turned this ambitious dream into a vibrant reality. From the very beginning, Jason poured not just his skills but his whole heart into the project, ensuring that every element was executed with precision, care, and excellence.<br/>Jason’s contributions have always gone far beyond the typical realm of technical support. His role was crucial in optimizing and streamlining various components of the educational programs Justin envisioned. From designing seamless student enrollment processes to developing promotional strategies that expanded the reach of their initiatives, Jason’s commitment to excellence was resolute. He understood that true success lay in the smallest details, and he dedicated himself fully to making sure every aspect ran smoothly and flawlessly.<br/>What truly sets Jason apart is his remarkable generosity and genuine passion for helping others. He is the person who goes above and beyond to support his colleagues, consistently giving more of himself than anyone could expect. Whether staying late to solve a technical challenge or mentoring a new team member with patience and enthusiasm, Jason’s selfless spirit shines through in everything he does. His unwavering support and kindness have made him an invaluable part of the company and a cherished colleague to everyone he encounters.<br/>To Justin, Jason has been much more than a collaborator. He has been a mentor, confidant, and true partner, providing the wisdom, insight, and steadfast support needed to turn their shared vision into reality. Jason’s dedication to the company and commitment to Justin’s dream have been fundamental in making their goals come alive. His influence resonates throughout the organization, embedding values of integrity, excellence, and community in every endeavor.<br/>The partnership between Jason and Justin exemplifies how the fusion of diverse skills, creative thinking, and a shared vision can lead to transformative results. Their collaboration is more than a professional alliance; it is a testament to what can be achieved when individuals unite with purpose and passion. Together, they have built an educational platform that extends beyond teaching—it empowers students, equipping them with essential tools and knowledge to succeed in an ever-changing world.<br/>Jason’s work has laid the foundation for a future where digital literacy and innovation are central to education. His dedication has created an ecosystem that prepares students to navigate and excel in a complex, dynamic environment. Through his unmatched commitment, generosity, and passion, Jason has left an enduring legacy that touches the company, Justin, and countless lives that have been influenced by their shared vision. He is, in every sense, irreplaceable—a cornerstone of the company’s success and a beacon of what it means to be dedicated, passionate, and selfless in the pursuit of greater good.<br/>Jason embodies the true essence of what it means to be a mentor, a leader, and a friend. His legacy of unwavering dedication, generosity, and pursuit of excellence will continue to inspire and guide the company for years to come, setting the standard for what it means to lead with heart and determination.",
          images: [
            "/images/Staff_Photos/Jason_M/image-4.jpg",
            "/images/Staff_Photos/Jason_M/image-1.jpg",
            "/images/Staff_Photos/Jason_M/image-6.jpg",
            "/images/Staff_Photos/Jason_M/image-3.jpg",
            "/images/Staff_Photos/Jason_M/image-5.jpg",
          ],
        },
      },
      {
        name: "Kimberly Nguyen",
        role: "Director of Honors and Presentations",
        bio: "Drives employee recognition through impactful presentations.",
        image: "/images/Staff_Photos/Kim.jpg",
        icons: [FaBasketballBall, GiSoccerBall, FaVolleyballBall, FaChess],
        moreInfo: {
          text: "Kim’s role as the Director of Honors and Presentations at IAC is the embodiment of dedication, compassion, and vision. Her work has cultivated a culture where recognition is woven into the fabric of the institution, ensuring that every instructor and student feels seen, valued, and celebrated. With each initiative she leads, Kim brings warmth and sincerity, enhancing the sense of belonging and pride within the IAC community.<br/>What sets Kim apart is her exceptional ability to tailor recognition to each individual. She knows that every instructor and student has their own unique journey, and she takes great care to acknowledge their accomplishments in ways that resonate deeply. From organizing surprise events to honor educators to crafting customized tokens that mark students’ milestones, Kim’s attention to detail and empathy shine through. She believes wholeheartedly that recognizing someone’s efforts can inspire confidence, foster motivation, and remind them of their worth—and she dedicates herself to making this belief a reality.<br/>One of the most impactful parts of Kim’s work is her creation of personalized awards and keepsakes for students. These items are more than just physical tokens; they represent achievement, growth, and pride. Kim understands the power that such thoughtful gestures can have—how a well-crafted certificate or a custom memento can encourage students to push further and celebrate their progress. These tokens carry a message: that their journey matters, and their efforts are noticed.<br/>Kim’s dedication extends far beyond the creation of awards; it is evident in the meaningful events she organizes to highlight student success. Under her leadership, these gatherings are more than ceremonies; they are immersive, heartfelt celebrations that honor both individual stories and collective achievements. Each presentation reflects her commitment to making sure every student’s contributions are acknowledged with genuine respect. These events become cherished memories that students and families carry long after their time at IAC.<br/>Beyond her professional expertise, Kim is known for her compassion and inclusivity. She has built an environment where recognition is not just an occasional gesture but a daily practice that elevates morale and strengthens community bonds. Her efforts to acknowledge the dedication and excellence of instructors inspire them to continue giving their best, creating a ripple effect that enhances the entire educational experience. Kim’s open and caring approach ensures that IAC remains a place where everyone feels encouraged to excel.<br/>Her influence permeates every interaction, from large-scale events to the smallest gestures. Kim’s philosophy of recognition goes beyond celebrating achievements—it’s about affirming each person’s value and honoring the unique path they’ve taken. Through her tireless dedication, Kim has become a cornerstone of the IAC community, fostering a legacy of appreciation that will last for years to come.Kim has redefined what it means to celebrate excellence at IAC. Her work, whether through grand ceremonies or thoughtful personal touches, has left an enduring impact on students, instructors, and the entire organization. Her leadership, compassion, and unwavering commitment make her an invaluable part of the institution and a true inspiration to all who have the privilege of knowing her.",
          images: [
            "/images/Staff_Photos/Kim/IMG_5667.png",
            "/images/Staff_Photos/Kim/IMG_5665.png",
            "/images/Staff_Photos/Kim/IMG_5669.png",
            "/images/Staff_Photos/Kim/IMG_5670.png",
            "/images/Staff_Photos/Kim/IMG_5671.png",
          ],
        },
      },
    ],
  },
  {
    category: "Lead Instructors",
    members: [
      {
        name: "Brian Kile",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Brian.jpg",
        icons: [FaBasketballBall, GiSoccerBall, FaFootballBall],
      },
      {
        name: "Bailey Johnson",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Bailey.jpg",
        icons: [FaBasketballBall],
      },
      {
        name: "David Fuchs",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/David.jpg",
        icons: [FaChess, FaPencil],
      },
      {
        name: "Dominick Pallatto",
        role: "Theater Instructor",
        image: "/images/Staff_Photos/Dominick.jpg",
        icons: [FaChess, FaTheaterMasks],
      },
      {
        name: "Gabriel Hernandez",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Gabe.jpg",
        icons: [FaChess, FaPencil, FaTheaterMasks],
      },
      {
        name: "Gino DeFalco",
        role: "Soccer Instructor",
        image: "/images/Staff_Photos/Gino.jpg",
        icons: [GiSoccerBall, FaVolleyballBall],
      },
      {
        name: "Jackie Rodriguez",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Jackie.jpg",
        icons: [FaBasketballBall, FaVolleyballBall],
      },
      {
        name: "James O'Leary",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/James_O.jpg",
        icons: [FaChess, FaPencil],
      },
      {
        name: "Jenny Dong",
        role: "Volleyball Instructor",
        image: "/images/Staff_Photos/Jenny.jpg",
        icons: [FaVolleyballBall],
      },
      {
        name: "Johnathan Rechter",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Johnathan.jpg",
        icons: [FaChess],
      },
      {
        name: "Tori Balnchard",
        role: "Volleyball Instructor",
        image: "/images/Staff_Photos/staff_photo_default.png",
        icons: [FaVolleyballBall, FaChess, FaPencil, FaTheaterMasks],
      },
      {
        name: "Nnamdi Agude",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Nnamdi.jpg",
        icons: [FaBasketballBall, FaChess, FaPencil, FaFootballBall],
      },
    ],
  },
  {
    category: "Assistant Instructors",
    members: [
      {
        name: "Alex Garber",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Alex.jpg",
        icons: [FaChess],
      },
      {
        name: "Andy Prendiville",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Andy.jpg",
        icons: [FaChess],
      },
      {
        name: "Bobby Xiao",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/staff_photo_default.png",
        icons: [FaChess],
      },
      {
        name: "Bodhi Armstrong",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Bodhi.jpg",
        icons: [FaBasketballBall],
      },
      {
        name: "Genesis Arroyo",
        role: "Flag Football Instructor",
        image: "/images/Staff_Photos/Genesis.jpg",
        icons: [FaFootballBall],
      },
      {
        name: "James Manley",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/James_M.png",
        icons: [FaBasketballBall],
      },
      {
        name: "Keshawn Carter",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Keshawn.jpg",
        icons: [FaBasketballBall, GiSoccerBall, FaChess, FaVolleyballBall],
      },
      {
        name: "Lawrence Brown",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/staff_photo_default.png",
        icons: [FaBasketballBall],
      },
      {
        name: "Novaleigh Bui",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Novaleigh_Bui.jpg",
        icons: [FaChess],
      },
      {
        name: "Max Evans",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Max_Evans.jpg",
        icons: [FaBasketballBall, FaPencil],
      },
      {
        name: "Michael Le",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Michael_Le.jpg",
        icons: [FaBasketballBall],
      },
      {
        name: "Zayaan Khan",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Zayaan.jpg",
        icons: [FaChess],
      },
      {
        name: "Bob Barone",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/staff_photo_default.png",
        icons: [FaBasketballBall],
      },

      {
        name: "Jack Clark",
        role: "Public Speaking Instructor",
        image: "/images/Staff_Photos/Jack_Clark.jpg",
        icons: [GiMicrophone, FaPencil, FaChess, FaTheaterMasks],
      },
    ],
  },
  {
    category: "Oversight",
    members: [
      {
        name: "Jessalyn Nguyen",
        role: "Administration Assistant",
        image: "/images/Staff_Photos/Jessalyn.jpg",
        icons: [FaBasketballBall, GiSoccerBall, FaVolleyballBall],
      },
      {
        name: "Middka Vicencio",
        role: "Administration Assistant",
        image: "/images/Staff_Photos/Middka.jpg",
        icons: [FaVolleyballBall],
      },
    ],
  },
];
