import {
  FaLaptopCode,
  FaChess,
  FaBasketballBall,
  FaTheaterMasks,
  FaVolleyballBall,
  FaFootballBall,
} from "react-icons/fa";
import { FaPencil } from "react-icons/fa6";
import { GiMicrophone, GiSoccerBall } from "react-icons/gi";
import { staffInfo } from "../types/information";

export const staffCategories: staffInfo[] = [
  {
    category: "Founder",
    members: [
      {
        name: "Justin Perez",
        role: "Co-Founder/ CEO",
        bio: "Leads with heart, empowering kids to thrive beyond limits",
        image: "/images/Staff_Photos/Justin_P.jpg",
        moreInfo: {
          email: "justin@iacafterschools.com",
          phone: "(714) 509-0069",
          bio: "A Vision Rooted in Purpose",
          text: "The inspiration behind Justin’s founding of IAC stems from a career marked by unwavering dedication and a legacy of meaningful accomplishments. Before launching IAC, Justin had already distinguished himself as an outstanding educator. His work received public recognition in the Tustin Weekly newspaper, where he was celebrated for his exceptional teaching. In that spotlight, he passionately described chess as more than just a game—it was a vehicle for developing life skills, enhancing strategic thinking, and fostering personal growth.<br /> This recognition was a pivotal moment that amplified his belief in the transformative power of education. His dedication was further acknowledged with the prestigious Millennium Leadership Award from Marin Millennium, honoring his outstanding leadership and his commitment to guiding and inspiring future generations. These formative experiences shaped his vision for IAC: an inclusive, forward-thinking educational platform designed to serve the diverse needs and interests of today’s learners.<br />Central to Justin’s educational philosophy is the conviction that learning must prepare students for real-world challenges. He envisioned IAC as a platform where students would not only excel academically but also gain the critical thinking, problem-solving, and resilience required for lifelong success. This holistic approach reflects his deep commitment to shaping well-rounded individuals ready to thrive both personally and professionally.<br />Driven by this mission, Justin actively works to build lasting partnerships and collaborations that align with IAC’s values. His passion for teaching and genuine care for each student fuel his determination to create a program where both educators and learners feel empowered. Looking ahead, Justin’s aspirations for IAC are ambitious. He aims to expand the program’s reach by forming new school partnerships and diversifying the curriculum to include a broader spectrum of subjects and enrichment opportunities.<br />This vision is not just about growth; it’s about creating a vibrant educational ecosystem that nurtures creativity, curiosity, and collaboration. Justin’s commitment to excellence and innovation is unwavering, and he remains dedicated to ensuring that IAC continues to be a beacon of educational opportunity for all students.<br />Justin’s journey is a testament to the power of passion, purpose, and perseverance. His legacy at IAC is one of inspiration, empowerment, and a relentless pursuit of excellence in education. As he continues to lead with heart and vision, Justin Perez is not just shaping the future of IAC; he is transforming the landscape of education itself. Within the IAC community, Justin is regarded as a trusted leader and source of inspiration. Instructors consistently seek his guidance, drawing on his experience and insight to elevate their own teaching practices. His mentorship has helped shape a culture of excellence, motivating staff to continually grow, reflect, and strive for impact. <br />Under Justin’s leadership, IAC has become more than an educational organization—it is a dynamic and evolving community rooted in purpose, innovation, and care. His visionary approach inspires everyone involved to dream big, challenge limits, and invest in their own potential. Justin’s influence is felt deeply across the IAC landscape. His commitment to continuous improvement and educational equity stands as a testament to the enduring power of leadership rooted in purpose. Through his efforts, IAC continues to enrich lives, expand opportunities, and cultivate a lasting love for learning in every student it serves.<br />Justin’s legacy is not just about the programs he has built or the accolades he has received; it is about the lives he has touched and the futures he has inspired. His unwavering belief in the potential of every student, combined with his relentless pursuit of excellence, ensures that IAC will continue to thrive as a leader in education for years to come.",
          images: [
            "/images/Staff_Photos/Justin/image16.jpg",
            "/images/Staff_Photos/Justin/image13.jpg",
            "/images/Staff_Photos/Justin/image00.jpg",
            "/images/Staff_Photos/Justin/image14.jpg",
            "/images/Staff_Photos/Justin/image11.jpg",
            "/images/Staff_Photos/Justin/image12.jpg",
            "/images/Staff_Photos/Justin/image20.jpg",
            "/images/Staff_Photos/Justin/image15.jpg",
            "/images/Staff_Photos/Justin/image19.jpg",
            "/images/Staff_Photos/Justin/image21.jpg",
            "/images/Staff_Photos/Justin/image17.jpg",
            "/images/Staff_Photos/Justin/image18.jpg",
          ],
        },
      },
      {
        name: "Jason Perez",
        role: "Co-Founder",
        bio: "Provides steadfast support to help kids thrive",
        image: "/images/Staff_Photos/Jason_P.jpg",
        moreInfo: {
          bio: "The Steadfast Co-Founder Behind IAC’s Foundation",
          text: "When Justin set out to build IAC, his brother, Jason Perez, was more than a supporter—he was a co-founder, a steadfast ally, and an irreplaceable force in bringing the vision to life. From the very beginning, Jason served as the steady anchor upon which Justin relied. His unwavering belief in the mission, coupled with his practical guidance and constant encouragement, played a crucial role in transforming an idea into a thriving educational platform.<br />Jason’s commitment to IAC was immediate and absolute. Recognizing the potential and promise in Justin’s vision, he devoted himself without hesitation to helping build something meaningful. While Justin stepped forward as the face of IAC—leading with creativity and a bold approach to education—Jason quietly worked behind the scenes to provide the structure, stability, and support necessary for the company to grow. His quiet strength, sound judgment, and tireless work ethic were instrumental in laying the foundation upon which IAC stands today. As co-founder, Jason brought a complementary skill set to Justin’s educational passion. His strategic insight, operational know-how, and deep dedication to the mission were vital to navigating the complexities of launching a new venture. He fully understood the sacrifices, the long hours, and the perseverance required—and he showed up each day with determination and resilience. Jason wasn’t just a silent partner; he was a builder, a problem-solver, and a motivator. His work behind the curtain amplified the company’s progress and allowed Justin to focus on innovation and instruction with full confidence in IAC’s stability.<br />Jason’s role extended far beyond business operations. He was Justin’s confidant, sounding board, and biggest advocate. His personal sacrifices reflected a profound commitment to both the mission and the people behind it. Jason believed deeply in the power of education to transform lives and committed himself fully to creating a space where that transformation could happen. His generosity of spirit and unwavering support propelled the company forward in its most critical early years.<br />Though he preferred to remain out of the spotlight, Jason’s influence can be felt throughout every chapter of IAC’s journey. His fingerprints are on every milestone, every initiative, and every triumph. His quiet leadership and consistent presence allowed IAC to grow with purpose, always grounded in the values the brothers shared. The partnership between Justin and Jason was one of harmony—vision met execution, creativity met strategy—and together, they established a foundation that would define the culture and success of IAC. Jason’s legacy at IAC is one of quiet determination and enduring impact. As co-founder, he was not just a behind-the-scenes contributor, but a pillar of the organization’s growth. His belief in the mission and his support of Justin’s dream were essential in turning a vision into a reality. The bond between the brothers—rooted in mutual respect, shared purpose, and unshakable dedication—created an environment where innovation and excellence could thrive.<br />Jason’s contributions are woven into the very fabric of IAC. From the trust built with families to the thoughtful structure of the curriculum, his influence is ever-present. He helped shape IAC into more than just an educational program—it became a community, a place of opportunity, and a model of what can be achieved through passion, partnership, and purpose. His impact continues to resonate, inspiring a culture of support, ambition, and integrity that remains central to IAC’s identity today.<br />Jason’s legacy is a testament to the power of collaboration and the strength of family. His unwavering support for Justin and the mission of IAC has left an indelible mark on the organization, ensuring that it will continue to thrive and inspire future generations. As IAC moves forward, Jason’s influence will remain a guiding force, reminding everyone involved of the importance of dedication, resilience, and the belief that together, anything is possible.",
          images: [],
        },
      },
    ],
  },
  {
    category: "Senior Instructors",
    members: [
      {
        name: "Tina Huynh",
        role: "Chief Operating Officer",
        bio: "Oversees operations, engineering, and administration seamlessly.",
        image: "/images/Staff_Photos/Tina.jpg",
        icons: [FaLaptopCode, FaPencil, FaChess],
        moreInfo: {
          bio: "A Champion for Education, Innovation, and Impact",
          email: "tina@iacafterschools.com",
          phone: "(714) 858-2418",
          text: "Tina’s journey into education began in middle school, where a volunteer opportunity at summer camps hosted by the University of California, Irvine, sparked a passion that would shape her future. It was there that she first experienced the joy of helping others learn—guiding peers through difficult concepts and witnessing the moment when understanding takes hold. These formative experiences instilled in her a deep sense of fulfillment and a desire to give back through teaching. Following high school, Tina expanded her efforts, dedicating her time to introducing elementary and middle school students to the exciting world of STEM. Her focus centered on software engineering and coding—fields she not only excelled in but was passionate about making accessible to young learners. She cherished the “aha” moments in her students, where confusion transformed into clarity, and was inspired by their growing enthusiasm to return to class eager to learn more.<br />As a first-generation software engineer, Tina brings a powerful sense of purpose to her work. Her commitment to mentoring the next generation is rooted in personal experience, and she is deeply driven to empower students to follow in her footsteps, break barriers, and make meaningful contributions to their communities. Her story serves as a beacon of possibility, especially for those who may not see themselves reflected in traditional tech spaces.<br />Tina’s personal qualities—resilience, integrity, and fierce advocacy for justice—make her an extraordinary role model. She is a principled leader who stands firm for what is right, guided by empathy, insight, and an unwavering moral compass. In high-pressure situations, she responds with clarity and assertiveness, bringing calm, confidence, and excellence to every challenge. Known for her dependability and drive, Tina consistently exceeds expectations and uplifts those around her.<br />At IAC, Tina plays a pivotal and multifaceted role. As a trusted advisor and collaborative partner to Justin, she contributes across a broad spectrum of responsibilities—from curriculum development and administrative oversight to staff training and organizational strategy. She is not only a vital contributor but a catalyst for progress, offering strategic insights that shape the direction of the organization and support data-informed decision-making at every level. In addition to her leadership within the educational sphere, Tina is a highly skilled full-stack web developer. She designed and developed IAC’s website from the ground up, and continues to optimize, enhance, and maintain the platform. Her technical expertise spans both front-end and back-end development, allowing her to create a seamless, responsive, and accessible digital experience. Her attention to user experience and visual design reflects her commitment to quality and functionality, making the website a true reflection of IAC’s mission and values.<br />Tina’s impact extends beyond her technical skills. She is a passionate advocate for diversity and inclusion in tech, actively working to create pathways for underrepresented groups to enter the field. Her commitment to equity and access is evident in her efforts to mentor aspiring engineers, providing guidance, support, and encouragement to those who may face barriers in their journey. Tina’s dedication to education, innovation, and social justice makes her an invaluable asset to IAC. Her leadership inspires others to strive for excellence, embrace their potential, and make a positive impact in their communities. As she continues to shape the future of IAC, Tina remains a beacon of hope and possibility for students and educators alike.<br />Tina’s deep understanding of instructional best practices, coupled with her high standards for excellence, make her an indispensable member of the IAC team. She combines strategic thinking with execution, vision with action, and technical mastery with educational insight. With her leadership, IAC continues to grow as an innovative, inclusive, and impactful educational organization.<br />Tina’s influence is felt throughout the organization, where she fosters a culture of collaboration, creativity, and continuous improvement. Her commitment to mentorship extends to new instructors, where she shares her expertise and insights to help them thrive in their roles. Tina’s dedication to building strong relationships with staff, students, and families creates a supportive environment that empowers everyone to succeed. Her work is a testament to the power of education as a force for positive change, and her legacy at IAC will continue to inspire future generations of learners and leaders. Tina's influence reaches far beyond the classroom or the codebase. She helps shape the culture of IAC—one defined by excellence, equity, and purpose. Through her guidance, expertise, and unwavering support, she ensures that IAC remains a place where students are empowered, educators are supported, and innovation thrives.<br />Tina’s journey is a powerful reminder of the impact one person can have on the lives of many. Her commitment to education, her passion for technology, and her dedication to social justice make her an extraordinary leader and advocate. As she continues to inspire others to reach their full potential, Tina Huynh stands as a shining example of what it means to lead with heart, vision, and purpose.",
          images: [
            "/images/Staff_Photos/Tina/image4.jpg",
            "/images/Staff_Photos/Tina/image9.jpg",
            "/images/Staff_Photos/Tina/image8.jpg",
            "/images/Staff_Photos/Tina/image3.jpg",
            "/images/Staff_Photos/Tina/image1.jpg",
            "/images/Staff_Photos/Tina/image2.jpg",
            "/images/Staff_Photos/Tina/image7.jpg",
            "/images/Staff_Photos/Tina/image6.jpg",
            "/images/Staff_Photos/Tina/image5.jpg",
          ],
        },
      },
      {
        name: "Mike Ash",
        role: "Director of Chess Operations",
        bio: "Leads chess operations with expertise and passion, inspiring growth and strategy.",
        image: "/images/Staff_Photos/Mike.jpg",
        icons: [GiSoccerBall, FaChess],
        moreInfo: {
          bio: "A Legacy of Loyalty, Leadership, and Lasting Impact",
          text: "Mike’s partnership with Justin spans over two decades, built on a foundation of mutual trust, unwavering respect, and a shared dedication to the transformative power of education. Throughout this enduring journey, Mike has been a constant source of strength—demonstrating exceptional loyalty, perseverance, and passion that have made him a cornerstone of IAC’s success.<br />What began as a collaborative effort between friends has evolved into a professional alliance defined by purpose and impact. Mike’s progression from a committed team member to a respected leader within the organization is marked by tireless work, steadfast resolve, and a genuine love for teaching. His unparalleled experience and skill as a chess instructor make him an educational force, but it is his heartfelt joy for teaching that truly defines his role. For Mike, education is not a job—it is a calling. His ability to inspire, engage, and empower his students is evident in every lesson he teaches, making him indispensable to our mission.<br />Mike’s contributions extend far beyond his deep knowledge of chess. He uses the game as a medium to teach invaluable life skills—resilience, critical thinking, patience, and sportsmanship. Each class becomes an opportunity for students to grow intellectually and emotionally. Mike’s empathetic teaching style and ability to connect with learners create a supportive environment where students feel seen, heard, and encouraged to reach their potential. In addition to his role in the classroom, Mike is a trusted mentor to fellow instructors. He leads by example, upholding the values that define IAC—integrity, excellence, and compassion. New instructors consistently turn to Mike for guidance, knowing they will receive not only technical insight but genuine support. His mentorship plays a critical role in onboarding and empowering staff, helping to ensure that the high standards of our program are consistently upheld across the board.<br />Mike is the embodiment of reliability and dedication. He doesn’t just meet expectations—he consistently exceeds them, setting a benchmark of excellence that inspires those around him. His consistency and commitment have earned him the reputation of being the most dependable instructor on our team. His classes are built on trust and excellence, forming the bedrock of many of our most successful programs.<br />Beyond his instructional role, Mike’s influence is deeply woven into the fabric of IAC. He is a quiet leader whose actions speak volumes—motivating colleagues, supporting growth, and reinforcing a culture of dedication and integrity. His presence brings reassurance and stability, enabling both new and seasoned instructors to flourish under his guidance and support.<br />Mike’s impact is most evident in the growth of our chess program. Under his stewardship, the program has flourished, attracting students from diverse backgrounds and skill levels. His ability to connect with young learners and instill a love for chess has led to remarkable increases in class sizes and student engagement. Mike’s teaching transcends the game itself; he fosters a sense of community, belonging, and shared purpose among students. They leave his classes not only as better chess players but as more confident individuals equipped with essential life skills.<br />Mike’s legacy at IAC is one of loyalty, leadership, and lasting impact. His unwavering commitment to education, mentorship, and community building has shaped the organization into what it is today. He is not just an instructor; he is a guiding light for students and staff alike. As IAC continues to grow and evolve, Mike’s influence will remain a cornerstone of our mission—ensuring that every student receives the support, encouragement, and inspiration they need to thrive.<br />Mike Ash is more than just a chess instructor; he is a mentor, a leader, and a friend. His dedication to education and his unwavering support for both students and colleagues make him an irreplaceable asset to IAC. As we look to the future, we are grateful for Mike’s contributions and excited to see how his legacy will continue to shape the lives of those he touches.<br />Mike Ash is more than a master educator—he is a mentor, a leader, and a visionary whose impact resonates throughout the organization. His dedication and passion continue to shape the future of IAC, ensuring that the values he upholds—excellence, compassion, and inspiration—remain at the core of everything we do. His legacy is one of lasting influence, touching the lives of countless students and colleagues and elevating the standard of what it means to teach with purpose.",
          images: [
            "/images/Staff_Photos/Mike/image1.jpg",
            "/images/Staff_Photos/Mike/image2.jpg",
            "/images/Staff_Photos/Mike/image9.jpg",
            "/images/Staff_Photos/Mike/image3.jpg",
            "/images/Staff_Photos/Mike/image4.jpg",
            "/images/Staff_Photos/Mike/image6.jpg",
            "/images/Staff_Photos/Mike/image7.jpg",
            "/images/Staff_Photos/Mike/image8.jpg",
            "/images/Staff_Photos/Mike/image5.jpg",
          ],
        },
      },
      {
        name: "Tommy Owens",
        role: "Director of Basketball Operations",
        bio: "Leads basketball operations with dedication and a passion for excellence.",
        image: "/images/Staff_Photos/Tommy.jpg",
        icons: [FaBasketballBall, FaChess],
        moreInfo: {
          bio: "Championing Growth, Excellence, and Mentorship",
          text: "Tommy’s journey with our organization is a testament to steadfast dedication, unwavering passion, and a profound commitment to mentorship. With years of distinguished service, Tommy has become a foundational figure within our community—someone whose influence extends across programs and generations. His versatile experience in chess, volleyball, soccer, and basketball reflects both his dynamic skill set and his deep-rooted dedication to youth development. Yet, it is on the basketball court where Tommy’s passion truly shines. His comprehensive understanding of the game—its techniques, strategies, and nuances—has earned him the title of Director of Basketball Operations, a role in which he not only leads but continually reimagines and expands the program’s impact.<br />As a leader, Tommy’s most defining quality is his commitment to mentorship. New instructors stepping into the world of teaching find in him a guiding light. He offers more than instruction—he shares a philosophy of education rooted in empathy, patience, and excellence. His mentorship extends from the granular—such as thoughtfully designed drills and gameplay mechanics—to the deeply personal, including classroom management strategies, communication techniques, and approaches to student engagement. Under Tommy’s guidance, instructors grow in skill and in confidence, empowered to lead with clarity and purpose. Tommy’s influence is not confined to the basketball court. He exemplifies leadership through action—fostering a culture of encouragement, openness, and collaboration. His well-known open-door policy is not just symbolic; it reflects his genuine commitment to being accessible, attentive, and present for his colleagues. Whether providing a listening ear, offering feedback, or working through challenges, Tommy is a trusted and dependable mentor whose presence strengthens the fabric of the team. His leadership style fosters trust, builds community, and reinforces a collective drive toward excellence. Deeply familiar with the inner workings and expectations of the organization, Tommy plays a crucial role in onboarding and guiding new team members. He shares institutional knowledge generously, helping others navigate their roles while championing professional development. His approach nurtures a culture of continual growth and mutual support—where everyone is encouraged to reach their full potential.<br />Tommy’s impact is most evident in the growth of our basketball program. Under his stewardship, the program has flourished, attracting students from diverse backgrounds and skill levels. His ability to connect with young learners and instill a love for basketball has led to remarkable increases in class sizes and student engagement. Tommy’s teaching transcends the game itself; he fosters a sense of community, belonging, and shared purpose among students. They leave his classes not only as better players but as more confident individuals equipped with essential life skills.<br />Tommy Owens is more than just a coach; he is a mentor, a leader, and a visionary whose impact resonates throughout the organization. His dedication and passion continue to shape the future of IAC, ensuring that the values he upholds—excellence, compassion, and inspiration—remain at the core of everything we do. His legacy is one of lasting influence, touching the lives of countless students and colleagues and elevating the standard of what it means to teach with purpose.<br />The transformative impact of Tommy’s work is most visible in the youth basketball programs he leads. Since his arrival, class sizes have more than tripled—a reflection of both the quality of his instruction and the strength of the relationships he builds. His students don’t just learn how to dribble, pass, and shoot; they develop discipline, teamwork, confidence, and sportsmanship. Tommy’s ability to connect with young athletes on a personal level sparks a love for the game that stays with them long after the final whistle. He cultivates a learning environment that is rigorous yet joyful, structured yet supportive—one where every child feels seen, challenged, and inspired.<br />Tommy’s legacy at IAC is one of loyalty, leadership, and lasting impact. His unwavering commitment to education, mentorship, and community building has shaped the organization into what it is today. He is not just an instructor; he is a guiding light for students and staff alike. As IAC continues to grow and evolve, Tommy’s influence will remain a cornerstone of our mission—ensuring that every student receives the support, encouragement, and inspiration they need to thrive.<br />Tommy Owens is more than a master educator—he is a mentor, a leader, and a visionary whose impact resonates throughout the organization. His dedication and passion continue to shape the future of IAC, ensuring that the values he upholds—excellence, compassion, and inspiration—remain at the core of everything we do. His legacy is one of lasting influence, touching the lives of countless students and colleagues and elevating the standard of what it means to teach with purpose.",
          images: [
            "/images/Staff_Photos/Tommy/image1.jpg",
            "/images/Staff_Photos/Tommy/image2.jpg",
            "/images/Staff_Photos/Tommy/image3.jpg",
            "/images/Staff_Photos/Tommy/image4.jpg",
            "/images/Staff_Photos/Tommy/image5.jpg",
            "/images/Staff_Photos/Tommy/image6.jpg",
            "/images/Staff_Photos/Tommy/image7.jpg",
            "/images/Staff_Photos/Tommy/image8.jpg",
            "/images/Staff_Photos/Tommy/image9.jpg",
          ],
        },
      },
      {
        name: "Layla Kurokawa",
        role: "Director of Performing Arts Operations",
        bio: "Manages performing arts operations with dedication and vision.",
        image: "/images/Staff_Photos/Layla.jpg",
        icons: [FaTheaterMasks],
        moreInfo: {
          bio: "Elevating the Arts and Empowering Every Voice",
          text: "Through her visionary leadership, Layla has created new opportunities for students to explore, express, and evolve artistically. Her efforts have not only broadened IAC’s educational scope but have also cultivated a space where students can connect with their passions, build confidence, and engage in meaningful self-expression. At the heart of Layla’s contributions is her unwavering commitment to mentorship and talent development. She plays a critical role in training new instructors, particularly those entering the performing arts division. With meticulous attention to detail and a deep understanding of IAC’s educational values, Layla ensures that every new hire is equipped to uphold the highest standards of teaching excellence. Her mentorship extends beyond technical instruction—she imparts the philosophies of creativity, inclusivity, and empathy that define IAC’s approach to education. Through her guidance, new instructors not only learn how to teach but how to inspire.<br />Layla’s influence radiates throughout every aspect of the performing arts programs. Her dedication to ongoing program development ensures that students consistently receive enriching, high-quality experiences. Her passion for the arts fuels a dynamic, student-centered environment—one where every learner feels empowered to grow, express, and contribute. Her work has laid the foundation for a vibrant artistic community within IAC, one that celebrates exploration, collaboration, and personal growth. <br />Known for her compassionate and inclusive approach, Layla prioritizes creating an environment where all students feel seen, supported, and valued. She understands that each learner brings a unique voice and perspective to the stage—whether they are naturally expressive or more reserved in their demeanor. In her classroom, there is no “one-size-fits-all” approach. Layla’s educational philosophy is grounded in the celebration of individuality. She tailors her instruction to highlight and uplift each student’s strengths, fostering an environment where creative and personal growth go hand in hand.<br />Nowhere is Layla’s impact more visible than in the end-of-session showcase, a hallmark of her program. Far more than a performance, the showcase is a celebration of each student’s journey—a culmination of their hard work, personal development, and artistic exploration. Designed with care and intention, the event ensures that every student, not just the most outgoing or advanced, is honored and recognized. It is a heartfelt testament to Layla’s belief that all students deserve to be celebrated for who they are and how far they’ve come.<br />In Layla’s classroom, artistic instruction is interwoven with the nurturing of self-esteem and personal identity. Her ability to recognize, elevate, and affirm the individuality of each student sets her apart as an extraordinary educator. Students leave her classes not only with enhanced skills in performance, movement, and expression, but also with a deeper sense of confidence and self-worth. Her impact extends far beyond the stage, leaving an indelible mark on the hearts and minds of those she teaches.<br />Layla’s impact is most evident in the growth of our performing arts programs. Under her stewardship, class sizes have flourished, attracting students from diverse backgrounds and skill levels. Her ability to connect with young learners and instill a love for the arts has led to remarkable increases in student engagement. Layla’s teaching transcends the stage; she fosters a sense of community, belonging, and shared purpose among students. They leave her classes not only as more skilled performers but as more confident individuals equipped with essential life skills.<br />Layla Kurokawa is more than just a performing arts instructor; she is a mentor, a leader, and a visionary whose impact resonates throughout the organization. Her dedication and passion continue to shape the future of IAC, ensuring that the values she upholds—excellence, compassion, and inspiration—remain at the core of everything we do. Her legacy is one of lasting influence, touching the lives of countless students and colleagues and elevating the standard of what it means to teach with purpose.",
          images: [
            "/images/Staff_Photos/Layla/image1.jpg",
            "/images/Staff_Photos/Layla/image2.jpg",
            "/images/Staff_Photos/Layla/image5.jpg",
            "/images/Staff_Photos/Layla/image3.jpg",
            "/images/Staff_Photos/Layla/image6.jpg",
            "/images/Staff_Photos/Layla/image7.jpg",
            "/images/Staff_Photos/Layla/image4.jpg",
            "/images/Staff_Photos/Layla/image8.jpg",
            "/images/Staff_Photos/Layla/image9.jpg",
          ],
        },
      },
      {
        name: "Cory Camama",
        role: "Director of Volleyball Operations",
        bio: "Oversees volleyball operations with extensive experience and expertise.",
        image: "/images/Staff_Photos/Cory.jpg",
        icons: [FaVolleyballBall],
        moreInfo: {
          bio: "Elevating Excellence Through Coaching and Mentorship",
          text: "Cory has swiftly distinguished himself as a vital force within our organization, bringing a powerful blend of passion, expertise, and leadership to the forefront of our sports programs—most notably in volleyball. With a profound understanding of the game—from foundational techniques to advanced strategies—Cory has become an indispensable coach, mentor, and role model for students and colleagues alike. His impact on our volleyball program has been transformative, reflected in the significant growth of his classes and the strong enthusiasm he inspires in his students.<br />Under Cory’s leadership, student participation in volleyball has flourished. His ability to connect with young athletes goes beyond instruction—he inspires a genuine love for the sport, fostering environments where students are both challenged and encouraged. In his classes, students refine critical technical skills such as serving, passing, setting, and spiking, while also developing key character traits like teamwork, discipline, and sportsmanship. For Cory, coaching is not limited to physical development—it’s about nurturing the whole athlete and imparting values that extend well beyond the court. What sets Cory apart even further is his unwavering commitment to mentorship. He plays an instrumental role in onboarding and supporting new instructors, offering not only technical knowledge but also insights into effective coaching methodologies and classroom management. Cory’s mentorship ensures that new hires are not only prepared to meet the demands of their roles but are empowered to exceed expectations. His open-door policy fosters a culture of support, inclusion, and continuous learning—qualities that make him a trusted leader within the team.<br />With his combination of technical skill, mentorship, and heartfelt dedication, Cory continues to be a driving force in the advancement of our sports programs. His presence is a true asset to the organization, and his legacy is one of empowerment, inspiration, and enduring impact.",
          images: [],
        },
      },
      {
        name: "Jason Michael",
        role: "Technical Advisor",
        bio: "Provides expert technical guidance and innovative solutions.",
        image: "/images/Staff_Photos/JasonM.jpg",
        icons: [FaLaptopCode],
        moreInfo: {
          bio: "Technical Advisor and Cornerstone of Innovation",
          text: "As Justin set out to realize his visionary goal of creating a transformative educational platform, Jason Michael emerged as the driving force behind its technical and operational success. From the outset, Jason brought not only his formidable expertise but also his unwavering commitment, boundless generosity, and deep passion for purposeful innovation. His dedication helped turn an ambitious vision into a thriving, impactful reality.<br />Jason’s role has extended far beyond conventional technical advising. He has been instrumental in architecting and refining the systems that power IAC’s educational programs. From developing seamless student enrollment processes to implementing data-driven promotional strategies, Jason ensured every element was designed with precision and executed with care. His attention to detail and insistence on excellence have been key to the organization’s growth and operational success. What truly sets Jason apart is his extraordinary generosity and heartfelt commitment to uplifting those around him. He is the kind of team member who consistently goes above and beyond—whether staying late to troubleshoot a challenge, offering strategic guidance, or mentoring new staff with patience and enthusiasm. His selfless approach and consistent support have made him not only an indispensable member of the team but also a beloved colleague.<br />To Justin, Jason has been far more than a collaborator. He is a trusted confidant, mentor, and partner. Jason’s insight, encouragement, and unwavering belief in the mission have been fundamental to bringing their shared vision to life. His influence runs deep within the fabric of the organization, embedding values of integrity, innovation, and community into every initiative and decision. The partnership between Jason and Justin exemplifies the power of collaboration rooted in purpose. Their combined strengths—blending visionary leadership with strategic execution—have built an educational ecosystem that goes beyond instruction. It empowers students, equips them with critical digital skills, and prepares them to thrive in an ever-evolving world.<br />Jason’s legacy is not only in the systems he helped build but in the culture of excellence and compassion he inspired. He laid the foundation for a future where digital literacy and innovation are central to education, and where every student has access to tools that open doors to opportunity. His work continues to impact the lives of students, educators, and families alike. He is, in every sense, irreplaceable—a cornerstone of the organization’s success and a shining example of what it means to lead with heart, humility, and conviction. <br />Jason Michael embodies the true spirit of mentorship, leadership, and friendship. His dedication, integrity, and generosity will continue to guide and inspire IAC for years to come—setting the gold standard for what it means to build with passion and lead with purpose.",
          images: [
            "/images/Staff_Photos/Jason_M/image-4.jpg",
            "/images/Staff_Photos/Jason_M/image-1.jpg",
            "/images/Staff_Photos/Jason_M/image-6.jpg",
            "/images/Staff_Photos/Jason_M/image-3.jpg",
            "/images/Staff_Photos/Jason_M/image-5.jpg",
          ],
        },
      },
      {
        name: "Kimberly Nguyen",
        role: "Director of Honors and Presentations",
        bio: "Drives employee recognition through impactful presentations.",
        image: "/images/Staff_Photos/Kim.jpg",
        icons: [FaBasketballBall, GiSoccerBall, FaVolleyballBall, FaChess],
        moreInfo: {
          bio: "Celebrating Excellence with Heart, Purpose, and Precision",
          text: "Kim has cultivated a culture where recognition is not an afterthought, but a central pillar of the IAC experience—one that ensures every instructor and student feels valued, seen, and celebrated. Through her initiatives, Kim has infused the organization with warmth, sincerity, and a deep sense of belonging, making IAC not just a place of learning, but a community of mutual respect and appreciation. What distinguishes Kim is her remarkable ability to personalize recognition in meaningful and memorable ways. She understands that every student and educator walks a unique path—and she honors that journey with deep intention. Whether orchestrating surprise celebrations for instructors or designing customized mementos for students, Kim approaches every gesture with care, creativity, and emotional intelligence. Her attention to detail reflects a profound understanding: that acknowledgment—when done thoughtfully—can fuel confidence, inspire perseverance, and affirm each individual’s worth.<br />Among Kim’s most impactful contributions is her creation of personalized awards and keepsakes for students. Far more than simple tokens, these items are symbols of achievement, progress, and pride. Each one tells a story of effort, growth, and transformation. Kim recognizes the power of tangible recognition and how it can serve as a lifelong reminder that a student’s journey mattered—that their milestones were seen and celebrated. Her commitment is perhaps most visible in the honor ceremonies and presentation events she leads. Under Kim’s guidance, these occasions transcend traditional recognition—they become heartfelt celebrations that uplift both the individual and the community. Every event she curates is rooted in authenticity and care, highlighting not only accomplishments, but the personal journeys behind them. Families, students, and staff leave these events not just with awards, but with lasting memories and a deep sense of pride.<br />Kim’s work is equally impactful behind the scenes. Her inclusive philosophy has helped embed a culture of recognition throughout the daily life of IAC. She advocates for continual acknowledgment of effort—both big and small—creating an environment where excellence is encouraged, appreciated, and celebrated at every level. Her leadership reminds instructors that their dedication is seen, and that their contributions matter—fueling a ripple effect of morale and motivation across the organization.<br />Beyond her professional achievements, Kim is cherished for her compassion, approachability, and unwavering support. She listens deeply, acts thoughtfully, and leads with integrity—qualities that have made her a trusted leader and a beloved member of the IAC community. Her ability to uplift others—through both grand gestures and small, sincere moments—has become a defining part of the institution’s identity.<br />Kimberly Nguyen has redefined what it means to honor success. Her legacy at IAC is one of celebration, inclusion, and lasting impact. Whether through a beautifully organized ceremony or a handwritten note of encouragement, her work affirms the value of every individual she encounters. She is not only the heart behind IAC’s recognition programs—she is a shining example of how honoring others can empower a community. Her presence continues to inspire students, staff, and families alike, leaving a meaningful imprint on every life she touches. <br />Kim’s influence is felt throughout the organization, where she fosters a culture of collaboration, creativity, and continuous improvement. Her commitment to mentorship extends to new instructors, where she shares her expertise and insights to help them thrive in their roles. Kim’s dedication to building strong relationships with staff, students, and families creates a supportive environment that empowers everyone to succeed. Her work is a testament to the power of education as a force for positive change, and her legacy at IAC will continue to inspire future generations of learners and leaders. Kim's influence reaches far beyond the classroom or the codebase. She helps shape the culture of IAC—one defined by excellence, equity, and purpose.",
          images: [
            "/images/Staff_Photos/Kim/IMG_5667.png",
            "/images/Staff_Photos/Kim/IMG_5665.png",
            "/images/Staff_Photos/Kim/IMG_5669.png",
            "/images/Staff_Photos/Kim/IMG_5670.png",
            "/images/Staff_Photos/Kim/IMG_5671.png",
          ],
        },
      },
    ],
  },
  {
    category: "Lead Instructors",
    members: [
      {
        name: "Brian Kile",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Brian.jpg",
        icons: [FaBasketballBall, GiSoccerBall, FaFootballBall],
      },
      {
        name: "Bailey Johnson",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Bailey.jpg",
        icons: [FaBasketballBall],
      },
      {
        name: "David Fuchs",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/David.jpg",
        icons: [FaChess, FaPencil],
      },
      {
        name: "Dominick Pallatto",
        role: "Theater Instructor",
        image: "/images/Staff_Photos/Dominick.jpg",
        icons: [FaChess, FaTheaterMasks],
      },
      {
        name: "Gabriel Hernandez",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Gabe.jpg",
        icons: [FaChess, FaPencil, FaTheaterMasks],
      },
      {
        name: "Gino DeFalco",
        role: "Soccer Instructor",
        image: "/images/Staff_Photos/Gino.jpg",
        icons: [GiSoccerBall, FaVolleyballBall],
      },
      {
        name: "Jackie Rodriguez",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Jackie.jpg",
        icons: [FaBasketballBall, FaVolleyballBall],
      },
      {
        name: "James O'Leary",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/James_O.jpg",
        icons: [FaChess, FaPencil],
      },
      {
        name: "Jenny Dong",
        role: "Volleyball Instructor",
        image: "/images/Staff_Photos/Jenny.jpg",
        icons: [FaVolleyballBall],
      },
      {
        name: "Johnathan Rechter",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Johnathan.jpg",
        icons: [FaChess],
      },
      {
        name: "Tori Balnchard",
        role: "Volleyball Instructor",
        image: "/images/Staff_Photos/staff_photo_default.png",
        icons: [FaVolleyballBall, FaChess, FaPencil, FaTheaterMasks],
      },
      {
        name: "Nnamdi Agude",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Nnamdi.jpg",
        icons: [FaBasketballBall, FaChess, FaPencil, FaFootballBall],
      },
    ],
  },
  {
    category: "Assistant Instructors",
    members: [
      {
        name: "Alex Garber",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Alex.jpg",
        icons: [FaChess],
      },
      {
        name: "Andy Prendiville",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Andy.jpg",
        icons: [FaChess],
      },
      {
        name: "Bobby Xiao",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/staff_photo_default.png",
        icons: [FaChess],
      },
      {
        name: "Bodhi Armstrong",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Bodhi.jpg",
        icons: [FaBasketballBall],
      },
      {
        name: "Genesis Arroyo",
        role: "Flag Football Instructor",
        image: "/images/Staff_Photos/Genesis.jpg",
        icons: [FaFootballBall],
      },
      {
        name: "James Manley",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/James_M.png",
        icons: [FaBasketballBall],
      },
      {
        name: "Keshawn Carter",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Keshawn.jpg",
        icons: [FaBasketballBall, GiSoccerBall, FaChess, FaVolleyballBall],
      },
      {
        name: "Lawrence Brown",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/staff_photo_default.png",
        icons: [FaBasketballBall],
      },
      {
        name: "Novaleigh Bui",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Novaleigh_Bui.jpg",
        icons: [FaChess],
      },
      {
        name: "Max Evans",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Max_Evans.jpg",
        icons: [FaBasketballBall, FaPencil],
      },
      {
        name: "Michael Le",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/Michael_Le.jpg",
        icons: [FaBasketballBall],
      },
      {
        name: "Zayaan Khan",
        role: "Chess Instructor",
        image: "/images/Staff_Photos/Zayaan.jpg",
        icons: [FaChess],
      },
      {
        name: "Bob Barone",
        role: "Basketball Instructor",
        image: "/images/Staff_Photos/staff_photo_default.png",
        icons: [FaBasketballBall],
      },

      {
        name: "Jack Clark",
        role: "Public Speaking Instructor",
        image: "/images/Staff_Photos/Jack_Clark.jpg",
        icons: [GiMicrophone, FaPencil, FaChess, FaTheaterMasks],
      },
    ],
  },
  {
    category: "Oversight",
    members: [
      {
        name: "Jessalyn Nguyen",
        role: "Administration Assistant",
        image: "/images/Staff_Photos/Jessalyn.jpg",
        icons: [FaBasketballBall, GiSoccerBall, FaVolleyballBall],
      },
      {
        name: "Middka Vicencio",
        role: "Administration Assistant",
        image: "/images/Staff_Photos/Middka.jpg",
        icons: [FaVolleyballBall],
      },
    ],
  },
];
