import { testimonialsInfo } from "../types/cards";
export const testimonials: testimonialsInfo[] = [
  {
    name: "Anonymous",
    title: "Theater Parent",
    school: "Arroyo Elementary School",
    class: "Theater",
    image: "/images/School_Icons/arroyo.png",
    text: "Enrolling my son in the performing arts course through IAC has been a transformative experience. The program emphasizes both technical ability and creative expression, and the instructors have a genuine passion for theater. Her newfound confidence in front of an audience is a testament to their dedication.",
  },
  {
    name: "Anonymous",
    title: "Parent",
    school: "Anonymous",
    image: "/images/School_Icons/hicks.png",
    class: "Chess",
    text: "...I am so grateful for your understanding and accommodation throughout this process. Your willingness to go above and beyond to resolve this issue speaks volumes about your exceptional customer service. Thank you",
  },
  {
    name: "Anonymous",
    title: "School Staff",
    school: "Peters Canyon Elementary School",
    class: "Chess",
    image: "/images/School_Icons/peterscanyon.png",
    text: "IAC's chess program has greatly enhanced student concentration and problem-solving abilities. The staff are patient and create a supportive environment that allows students to thrive, regardless of their skill level. The program reinforces the lessons we teach.",
  },
  {
    name: "Anonymous",
    title: "Chess Parent",
    school: "Peters Canyon Elementary School",
    class: "Chess",
    image: "/images/School_Icons/peterscanyon.png",
    text: "I am at a loss for words; upon reading [Justin's] email, I couldn't help but feel an overwhelming sense of relief. The appreciation of the scholarship is truly a blessing to me, and the many years of [my son's] participation have made such an impact on his life! People like [Justin] really do make such an impact.",
  },
  {
    name: "Anonymous",
    title: "Theater Parent",
    school: "Arroyo Elementary School",
    class: "Theater",
    image: "/images/School_Icons/arroyo.png",
    text: "Watching my once-shy daughter perform confidently on stage was a dream come true. The theater staff at IAC excel at nurturing talent and fostering self-esteem. Her enthusiasm for school has grown significantly, and she comes home eager to share her experiences.",
  },
  {
    name: "Anonymous",
    title: "Soccer Parent",
    school: "Hicks Elementary School",
    class: "Soccer",
    image: "/images/School_Icons/hicks.png",
    text: "The soccer program is outstanding! The coaches are highly skilled and serve as excellent role models. The staff ensure that every child feels included and valued, which has greatly boosted my son's confidence. I am deeply grateful to IAC for the peace of mind they provide.",
  },
  {
    name: "Anonymous",
    title: "Chess Parent",
    school: "Hicks Canyon Elementary School",
    class: "Chess",
    image: "/images/School_Icons/hicks.png",
    text: "...my sons attend Hicks Canyon Elementary and have been in several after-school programs provided by IAC. They always have a great time, and [instructors] always go the extra mile to help my son, Taylor, so he can get the most out of the program. Also, when I was having a financially difficult time last year, [Justin] gave us a big discount, telling me that it was their passion to help out the community. I'm happy to say that I no longer need the financial assistance for the program, but it was so meaningful to feel that someone in the community cared about my kids' well-being and opportunities to experience wholesome activities.",
  },
  {
    name: "Anonymous",
    title: "Creative Writing Parent",
    school: "Historic Anaheim Elementary School",
    class: "Creative Writing",
    image: "/images/School_Icons/fairmont.png",
    text: "The creative writing program at IAC has been transformative for my daughter. The workshops have elevated her skills to new heights. As a working parent, finding quality after-school care was challenging until we discovered IAC. The diverse range of activities keeps my son engaged, and I greatly value the balance between education and fun that the program offers.",
  },
  {
    name: "Anonymous",
    title: "Chess Parent",
    school: "Peters Canyon Elementary School",
    class: "Chess",
    image: "/images/School_Icons/peterscanyon.png",
    text: "Due to one of my children's severe food allergies, we have been denied by multiple camps and classes who did not want the risk of having them as a student. However, Justin was very responsive and collaborated with me on ways to adapt the class to be a safe space. Both of my kids love learning about chess and practicing among their peers. I'm excited they are able to learn a game that teaches critical thinking and persistence.",
  },
  {
    name: "Anonymous",
    title: "School Staff",
    school: "North Tustin Elementary School",
    class: "Chess",
    image: "/images/School_Icons/fairmont.png",
    text: "The chess club facilitated by IAC has become a highlight for many students. The program has significantly improved students' critical thinking skills and had a positive effect on their behavior and social skills.",
  },
  {
    name: "Anonymous",
    title: "Creative Writing Parent",
    school: "Historic Anaheim Elementary School",
    class: "Creative Writing",
    image: "/images/School_Icons/fairmont.png",
    text: "The creative writing classes at IAC have ignited my child's passion for storytelling. The instructors not only teach the fundamentals of writing but also inspire a love for literature and self-expression. It has been truly encouraging to see him develop a confident voice.",
  },
  {
    name: "Anonymous",
    title: "Parent",
    school: "Hicks Elementary School",
    class: "Basketball",
    image: "/images/School_Icons/hicks.png",
    text: "I can’t speak highly enough of the basketball program at IAC. My daughter eagerly looks forward to every practice, excited to develop her abilities and engage with her teammates. The program strikes a perfect balance between skill development, teamwork, and fun.",
  },
];
