import { testimonialsInfo } from "../types/cards";
export const testimonials: testimonialsInfo[] = [
  {
    name: "Anonymous",
    title: "Theater Parent",
    school: "Arroyo Elementary School",
    class: "Theater",
    image: "/images/School_Icons/arroyo.png",
    text: "Enrolling my son in the performing arts course through IAC has been a transformative experience. The program emphasizes both technical ability and creative expression, and the instructors have a genuine passion for theater. Her newfound confidence in front of an audience is a testament to their dedication.",
  },
  {
    name: "Anonymous",
    title: "Parent",
    school: "Anonymous",
    image: "/images/School_Icons/hicks.png",
    class: "Chess",
    text: "...I am so grateful for your understanding and accommodation throughout this process. Your willingness to go above and beyond to resolve this issue speaks volumes about your exceptional customer service. Thank you",
  },
  {
    name: "Anonymous",
    title: "School Staff",
    school: "Peters Canyon Elementary School",
    class: "Chess",
    image: "/images/School_Icons/peterscanyon.png",
    text: "IAC's chess program has greatly enhanced student concentration and problem-solving abilities. The staff are patient and create a supportive environment that allows students to thrive, regardless of their skill level. The program reinforces the lessons we teach.",
  },
  {
    name: "Anonymous",
    title: "Chess Parent",
    school: "Peters Canyon Elementary School",
    class: "Chess",
    image: "/images/School_Icons/peterscanyon.png",
    text: "I am at a loss for words; upon reading [Justin's] email, I couldn't help but feel an overwhelming sense of relief. The appreciation of the scholarship is truly a blessing to me, and the many years of [my son's] participation have made such an impact on his life! People like [Justin] really do make such an impact.",
  },
  {
    name: "Anonymous",
    title: "Theater Parent",
    school: "Arroyo Elementary School",
    class: "Theater",
    image: "/images/School_Icons/arroyo.png",
    text: "Watching my once-shy daughter perform confidently on stage was a dream come true. The theater staff at IAC excel at nurturing talent and fostering self-esteem. Her enthusiasm for school has grown significantly, and she comes home eager to share her experiences.",
  },
  {
    name: "Anonymous",
    title: "Soccer Parent",
    school: "Hicks Elementary School",
    class: "Soccer",
    image: "/images/School_Icons/hicks.png",
    text: "The soccer program is outstanding! The coaches are highly skilled and serve as excellent role models. The staff ensure that every child feels included and valued, which has greatly boosted my son's confidence. I am deeply grateful to IAC for the peace of mind they provide.",
  },
  {
    name: "Anonymous",
    title: "Chess Parent",
    school: "Hicks Canyon Elementary School",
    class: "Chess",
    image: "/images/School_Icons/hicks.png",
    text: "...my sons attend Hicks Canyon Elementary and have been in several after-school programs provided by IAC. They always have a great time, and [instructors] always go the extra mile to help my son, Taylor, so he can get the most out of the program. Also, when I was having a financially difficult time last year, [Justin] gave us a big discount, telling me that it was their passion to help out the community. I'm happy to say that I no longer need the financial assistance for the program, but it was so meaningful to feel that someone in the community cared about my kids' well-being and opportunities to experience wholesome activities.",
  },
  {
    name: "Anonymous",
    title: "Creative Writing Parent",
    school: "Historic Anaheim Elementary School",
    class: "Creative Writing",
    image: "/images/School_Icons/fairmont.png",
    text: "The creative writing program at IAC has been transformative for my daughter. The workshops have elevated her skills to new heights. As a working parent, finding quality after-school care was challenging until we discovered IAC. The diverse range of activities keeps my son engaged, and I greatly value the balance between education and fun that the program offers.",
  },
  {
    name: "Anonymous",
    title: "Chess Parent",
    school: "Peters Canyon Elementary School",
    class: "Chess",
    image: "/images/School_Icons/peterscanyon.png",
    text: "Due to one of my children's severe food allergies, we have been denied by multiple camps and classes who did not want the risk of having them as a student. However, Justin was very responsive and collaborated with me on ways to adapt the class to be a safe space. Both of my kids love learning about chess and practicing among their peers. I'm excited they are able to learn a game that teaches critical thinking and persistence.",
  },
  {
    name: "Anonymous",
    title: "School Staff",
    school: "North Tustin Elementary School",
    class: "Chess",
    image: "/images/School_Icons/fairmont.png",
    text: "The chess club facilitated by IAC has become a highlight for many students. The program has significantly improved students' critical thinking skills and had a positive effect on their behavior and social skills.",
  },
  {
    name: "Anonymous",
    title: "Creative Writing Parent",
    school: "Historic Anaheim Elementary School",
    class: "Creative Writing",
    image: "/images/School_Icons/fairmont.png",
    text: "The creative writing classes at IAC have ignited my child's passion for storytelling. The instructors not only teach the fundamentals of writing but also inspire a love for literature and self-expression. It has been truly encouraging to see him develop a confident voice.",
  },
  {
    name: "Anonymous",
    title: "Parent",
    school: "Hicks Elementary School",
    class: "Basketball",
    image: "/images/School_Icons/hicks.png",
    text: "I can't speak highly enough of the basketball program at IAC. My daughter eagerly looks forward to every practice, excited to develop her abilities and engage with her teammates. The program strikes a perfect balance between skill development, teamwork, and fun.",
  },
  {
    name: "Anonymous",
    title: "Volleyball Parent",
    school: "Peters Canyon Elementary School",
    class: "Volleyball",
    image: "/images/School_Icons/peterscanyon.png",
    text: "The volleyball program has been incredible for my daughter's physical development and teamwork skills. The coaches create a supportive environment where every player feels valued, regardless of their experience level. She's learned so much about communication, leadership, and perseverance through this program.",
  },
  {
    name: "Anonymous",
    title: "Comic Book Parent",
    school: "Arroyo Elementary School",
    class: "Comic Book",
    image: "/images/School_Icons/arroyo.png",
    text: "My son has always been a reluctant reader, but the comic book creation class at IAC has changed everything. He's now writing his own stories and illustrating characters with such enthusiasm. The instructors have found a way to combine creativity with literacy that truly resonates with him.",
  },
  {
    name: "Anonymous",
    title: "Public Speaking Parent",
    school: "Historic Anaheim Elementary School",
    class: "Public Speaking",
    image: "/images/School_Icons/fairmont.png",
    text: "The public speaking program has been a game-changer for my shy daughter. The instructors use engaging activities and provide a safe space for kids to build confidence. She now speaks up in class and has even volunteered to give presentations at school. I'm amazed at her transformation.",
  },
  {
    name: "Anonymous",
    title: "Basketball Parent",
    school: "Peters Canyon Elementary School",
    class: "Basketball",
    image: "/images/School_Icons/peterscanyon.png",
    text: "The basketball coaches at IAC focus on fundamentals while keeping the atmosphere fun and encouraging. My son has improved his coordination and learned valuable lessons about teamwork and sportsmanship. The program has also helped him make new friendships.",
  },
  {
    name: "Anonymous",
    title: "Volleyball Parent",
    school: "Hicks Elementary School",
    class: "Volleyball",
    image: "/images/School_Icons/hicks.png",
    text: "I was impressed by how quickly my daughter picked up volleyball skills in this program. The instructors break down complex techniques into manageable steps, and the positive reinforcement keeps the kids motivated. She's gained confidence not just in sports, but in trying new challenges overall.",
  },
  {
    name: "Anonymous",
    title: "Soccer Parent",
    school: "Arroyo Elementary School",
    class: "Soccer",
    image: "/images/School_Icons/arroyo.png",
    text: "The soccer program has helped my son develop not only his athletic abilities but also his social skills. The coaches emphasize fair play and respect for teammates and opponents alike. He looks forward to every session and has made lasting friendships through the program.",
  },
  {
    name: "Anonymous",
    title: "Comic Book Parent",
    school: "Hicks Elementary School",
    class: "Comic Book",
    image: "/images/School_Icons/hicks.png",
    text: "This comic book class has unlocked my daughter's imagination in ways I never expected. She's learning about storytelling, character development, and visual design all while having fun. The instructors encourage creativity while teaching practical skills that will benefit her in many areas.",
  },
  {
    name: "Anonymous",
    title: "School Staff",
    school: "Arroyo Elementary School",
    class: "Public Speaking",
    image: "/images/School_Icons/arroyo.png",
    text: "The public speaking program has had a noticeable impact on our students' classroom participation. Students who were previously hesitant to speak up are now more confident in sharing their ideas. The skills they're learning extend far beyond the program itself.",
  },
  {
    name: "Anonymous",
    title: "Theater Parent",
    school: "Peters Canyon Elementary School",
    class: "Theater",
    image: "/images/School_Icons/peterscanyon.png",
    text: "My daughter has blossomed in the theater program. Not only has she gained confidence on stage, but she's also improved her reading skills and emotional expression. The instructors create an inclusive environment where every child can shine, regardless of their natural abilities.",
  },
  {
    name: "Anonymous",
    title: "Creative Writing Parent",
    school: "Arroyo Elementary School",
    class: "Creative Writing",
    image: "/images/School_Icons/arroyo.png",
    text: "The creative writing workshops have helped my son discover his voice as a writer. The instructors provide constructive feedback while encouraging experimentation with different styles and genres. His vocabulary has expanded significantly, and he now sees writing as a form of self-expression rather than a chore.",
  },
  {
    name: "Anonymous",
    title: "Public Speaking Parent",
    school: "Peters Canyon Elementary School",
    class: "Public Speaking",
    image: "/images/School_Icons/peterscanyon.png",
    text: "I enrolled my son in public speaking to help with his confidence, and the results have exceeded my expectations. He's learned to organize his thoughts clearly and present them with poise. These skills have helped him in all areas of his academic life, and he's even considering joining the school debate team.",
  },
  {
    name: "Anonymous",
    title: "Comic Book Parent",
    school: "Peters Canyon Elementary School",
    class: "Comic Book",
    image: "/images/School_Icons/peterscanyon.png",
    text: "The comic book creation class has been perfect for my artistic child. She's learning about visual storytelling, character design, and narrative structure in a format that genuinely excites her. The instructors balance creative freedom with technical instruction beautifully.",
  },
  {
    name: "Anonymous",
    title: "Basketball Parent",
    school: "Arroyo Elementary School",
    class: "Basketball",
    image: "/images/School_Icons/arroyo.png",
    text: "The basketball program has taught my daughter so much more than just sports skills. She's learned about dedication, practice, and supporting her teammates. The coaches create an environment where improvement is celebrated regardless of natural talent level.",
  },
  {
    name: "Anonymous",
    title: "Volleyball Parent",
    school: "Arroyo Elementary School",
    class: "Volleyball",
    image: "/images/School_Icons/arroyo.png",
    text: "My son joined volleyball with no prior experience, and the patient instruction from IAC coaches has been remarkable. They've helped him develop hand-eye coordination while building his confidence in a team sport. The positive atmosphere makes every practice enjoyable.",
  },
  {
    name: "Anonymous",
    title: "Soccer Parent",
    school: "Peters Canyon Elementary School",
    class: "Soccer",
    image: "/images/School_Icons/peterscanyon.png",
    text: "The soccer program has been wonderful for my daughter's physical fitness and social development. The coaches emphasize skill-building while maintaining a fun, supportive environment. She's made great friends and learned valuable lessons about teamwork and perseverance.",
  },
  {
    name: "Anonymous",
    title: "School Staff",
    school: "Historic Anaheim Elementary School",
    class: "Creative Writing",
    image: "/images/School_Icons/fairmont.png",
    text: "The creative writing program has significantly improved our students' overall writing abilities. We've noticed enhanced creativity, better organization of ideas, and increased enthusiasm for writing assignments in regular classroom work. The program complements our academic curriculum perfectly.",
  },
  {
    name: "Anonymous",
    title: "Parent",
    school: "Hicks Elementary School",
    class: "Theater",
    image: "/images/School_Icons/hicks.png",
    text: "The theater program has helped my introverted son come out of his shell in the most wonderful way. He's gained confidence, improved his public speaking, and developed a love for literature through script work. The supportive environment created by the instructors makes all the difference.",
  },
];
